---
title: "Microarray Analysis Pipeline"
author: "Sam Thilmany"
date: '2022-06-23'
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r general-config}
# #####################
# General configuration
# #####################

baseDir <- getwd()
targetsFile <- 'targets.tsv'

options(scipen = 99)
require(limma)
library(kableExtra)
```



```{r annotation-file}
# ##################################
# Read or create the annotation file
# ##################################

today <- format(Sys.Date(), format="%Y-%m")

annotationFile <- paste0('Human_agilent_sureprint_g3_ge_8x60k_v2_', gsub("-", "_", as.character(today)), '.tsv')

if (!file.exists(annotationFile)) {
  source("Annotation-File-Generator.R", local = knitr::knit_global())
}
```



```{r read-in-data}
# ################
# Read in the data
# ################

# Targets
targetinfo <- readTargets(targetsFile, sep = '\t')

# SureScan Data
# converts the data to an EListRaw object
project <- read.maimages(
  targetinfo,
  source = 'agilent.median',
  green.only = TRUE,
  other.columns = 'gIsWellAboveBG'
)
colnames(project) <- gsub('raw\\/', '', colnames(project))
```


```{r qc-plots-raw-data}
# ###############################
# Generate QC plots from raw data
# ###############################

# Create a folder for QC graphs
dir_raw_data_qc_graphs <- paste0(baseDir, "/QC/raw-data")

if (!dir.exists(dir_raw_data_qc_graphs)) {
  dir.create(dir_raw_data_qc_graphs)
}

setwd(dir_raw_data_qc_graphs)
getwd()

# histograms, box, and density plots - use your own code

setwd(baseDir)
```


```{r probe-annotation}
# ###################
# Annotate the probes
# ###################

annotLookup <- read.csv(
  annotationFile,
  header = TRUE,
  sep = '\t',
  stringsAsFactors = FALSE
)

colnames(annotLookup)[1] <- 'AgilentID'

annotLookup <- annotLookup[which(annotLookup$AgilentID %in% project$genes$ProbeName),]
annotLookup <- annotLookup[match(project$genes$ProbeName, annotLookup$AgilentID),]
table(project$genes$ProbeName == annotLookup$AgilentID) # check that annotations are aligned

project$genes$AgilentID <- annotLookup$AgilentID
project$genes$wikigene_description <- annotLookup$wikigene_description
project$genes$ensembl_gene_id <- annotLookup$ensembl_gene_id
project$genes$entrezgene <- annotLookup$entrezgene
project$genes$gene_biotype <- annotLookup$gene_biotype
project$genes$external_gene_name <- annotLookup$external_gene_name
```


```{r background-correction}
# #############################
# Perform background correction
# #############################

project.bgcorrect <- backgroundCorrect(project, method = 'normexp')
```


```{r normalize-data}
# ##############
# Normalize data
# ##############

project.bgcorrect.norm <- normalizeBetweenArrays(project.bgcorrect, method = 'quantile')
```


```{r filter-probes}
# ##########################
# Filter out control probes, 
# those with no symbol, 
# and those that fail
# ##########################

Control <- project.bgcorrect.norm$genes$ControlType == 1L
NoSymbol <- is.na(project.bgcorrect.norm$genes$external_gene_name)
IsExpr <- rowSums(project.bgcorrect.norm$other$gIsWellAboveBG > 0) >= 4

project.bgcorrect.norm.filt <- project.bgcorrect.norm[!Control & !NoSymbol & IsExpr, ]
dim(project.bgcorrect.norm)
dim(project.bgcorrect.norm.filt)
```


```{r remove-not-needed-annotation-columns}
# ##########################################
# Remove annotation columns no longer needed
# ##########################################

head(project.bgcorrect.norm.filt$genes)
project.bgcorrect.norm.filt$genes <- project.bgcorrect.norm.filt$genes[,c(
  'ProbeName','wikigene_description','ensembl_gene_id','entrezgene','gene_biotype','external_gene_name'
)]
head(project.bgcorrect.norm.filt$genes)
```


```{r reduce-replicates-to-mean}
# ############################################
# Replace replicate probes with the mean value
# ############################################

project.bgcorrect.norm.filt.mean <- avereps(project.bgcorrect.norm.filt,
  ID = project.bgcorrect.norm.filt$genes$ProbeName)

dim(project.bgcorrect.norm.filt)
dim(project.bgcorrect.norm.filt.mean)
```

```{r qc-plots-norm-data}
# ######################################
# Generate QC plots from normalized data
# ######################################

# Create a folder for QC graphs
dir_norm_data_qc_graphs <- paste0(baseDir, "/QC/norm-data")

if (!dir.exists(dir_norm_data_qc_graphs)) {
  dir.create(dir_norm_data_qc_graphs)
}

setwd(dir_norm_data_qc_graphs)
getwd()

# histograms, box, and density plots - use your own code

setwd(baseDir)
```

